#ifndef __LIBDEB_COMPRESSION_H
#define __LIBDEB_COMPRESSION_H

#include <debian/libdeb/config.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	DEB_COMPRESSION_INVALID,
	DEB_COMPRESSION_NONE,
	DEB_COMPRESSION_GZIP,
	DEB_COMPRESSION_BZIP2,	
	DEB_COMPRESSION_LZMA,
	DEB_COMPRESSION_XZ,
	DEB_COMPRESSION_UU,
	DEB_COMPRESSION_RPM,
	DEB_COMPRESSION_LZIP,
	DEB_COMPRESSION_LRZIP
} DEB_COMPRESSION;

#define DEB_COMPRESSION_COUNT 14

LIBDEB_EXPORT const char * deb_compression_get_name(DEB_COMPRESSION compression);

#ifdef __cplusplus
}
#endif

#endif /* __LIBDEB_COMPRESSION_H */